# ✅ .github/workflows/docker-build.yml
# ----------------------------------
name: CI - Build & Lint
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Lint (placeholder)
      run: echo "Linting code..."
    - name: Docker Build
      run: docker build -t chip-assistant .